# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('no_control', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(default=123, max_length=64)),
                ('semestre', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido_paterno', models.CharField(max_length=128)),
                ('apellido_materno', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AvanceMateria',
            fields=[
                ('id_avance', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('periodo', models.CharField(max_length=128)),
                ('oportunidad', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('clave', models.CharField(max_length=128)),
                ('acreditado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=250)),
                ('ano', models.IntegerField()),
                ('dia_semana', models.IntegerField()),
                ('hora_comienzo', models.IntegerField()),
                ('hora_final', models.IntegerField()),
                ('fecha_de_devolucion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido_paterno', models.CharField(max_length=250)),
                ('apellido_materno', models.CharField(max_length=250)),
                ('no_empleado', models.CharField(max_length=250)),
                ('plaza', models.CharField(max_length=250)),
                ('correo_electronico', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=250)),
                ('carrera', models.CharField(max_length=250)),
                ('nivel_de_estudios', models.CharField(max_length=250)),
                ('especialidad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id_kardex', models.AutoField(primary_key=True, serialize=False)),
                ('avance', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=128)),
                ('semestre', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=128)),
                ('creditos', models.IntegerField()),
                ('horas_practicas', models.IntegerField()),
                ('horas_teoricas', models.IntegerField()),
                ('previous', models.IntegerField(default=0)),
                ('next', models.IntegerField(default=0)),
                ('especialidad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Area')),
                ('materia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Carrera')),
                ('materia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Area')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Docente')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Evidencia')),
            ],
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Materia'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Docente'),
        ),
        migrations.AddField(
            model_name='avancemateria',
            name='profesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Docente'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='avance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.AvanceMateria'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='materia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Materia'),
        ),
    ]
