# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('no_control', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('ap_pat', models.CharField(max_length=128)),
                ('ap_mat', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AvanceMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('oportunidad', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('intentos', models.IntegerField(default=0)),
                ('pasado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.IntegerField(default=0)),
                ('no_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=128)),
                ('periodo', models.CharField(max_length=128)),
                ('profesor', models.CharField(max_length=128)),
                ('clave', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaInfo',
            fields=[
                ('id_materia', models.IntegerField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('creditos', models.IntegerField()),
                ('horasPractica', models.IntegerField()),
                ('horasTeoria', models.IntegerField()),
                ('previous', models.IntegerField(default=0)),
                ('next', models.IntegerField(default=0)),
                ('id_especialidad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='avancemateria',
            name='id_materia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Materia'),
        ),
        migrations.AddField(
            model_name='avancemateria',
            name='no_control',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Alumno'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='materias',
            field=models.ManyToManyField(to='home.MateriaInfo'),
        ),
    ]
