# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnomateria',
            name='avance',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AvanceMateria'),
        ),
    ]
