# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoMateriaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.MateriaInfo')),
                ('no_control', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Alumno')),
            ],
        ),
    ]
