# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alumnomateriainfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='materias',
        ),
    ]
