# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_alumno_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiainfo',
            name='id_materia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
