# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171103_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancemateria',
            name='id_materiainfo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.MateriaInfo'),
        ),
        migrations.AddField(
            model_name='materiainfo',
            name='semestra',
            field=models.IntegerField(default=0),
        ),
    ]
