# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171109_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(default=123, max_length=64),
        ),
    ]
