# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alumno_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
    ]
