# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alumno_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
